[package]
name = "easy-suricata"
version = "0.1.0"
authors = ["Jason Ish <ish@unx.ca>"]
edition = "2018"

# Some tweaks to reduce binary size.
[profile.release]
opt-level = "z"
lto = true
codegen-units = 1

[dependencies]
anyhow = "1.0.34"
regex = "1.4.2"
serde_json = "1.0.64"
serde = { version = "1.0.126", features = ["derive"] }
clap = "3.0.0-beta.2"
os-release = "0.1.0"
tracing = { version = "0.1.26", default_features = false, features = [] }
tracing-subscriber = { version = "0.2.18", default_features = false, features = ["fmt", "ansi"] }
libc = "0.2.97"
termcolor = "1.1.2"
